# Generated by Django 2.2.8 on 2020-02-02 16:53

import apps.staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='title',
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name_en',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name_fa',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='group_title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name_en',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name_fa',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='team_title',
            field=models.CharField(default='_', max_length=256),
        ),
        migrations.AddField(
            model_name='staff',
            name='url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(upload_to=apps.staff.models.Staff.upload_path),
        ),
    ]
