# Generated by Django 2.2.9 on 2020-02-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(default='', max_length=128),
        ),
    ]
