# Generated by Django 2.2.8 on 2020-01-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0003_auto_20200124_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('accepted', 'Invitation Accepted'), ('rejected', 'Invitation Rejected'), ('not_answered', 'Invitation Not Answered')], default='not_answered', max_length=50),
        ),
    ]
