# Generated by Django 2.2.8 on 2020-01-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0004_invitation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='challenge',
        ),
    ]
