# Generated by Django 2.2.8 on 2020-01-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0004_invitation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='participants', to='participation.Team'),
        ),
    ]
