# Generated by Django 2.2.8 on 2020-01-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_auto_20200126_1222'),
        ('participation', '0005_remove_team_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='challenge',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='challenge.Challenge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ManyToManyField(blank=True, null=True, related_name='teams', to='challenge.Tournament'),
        ),
    ]
