# Generated by Django 2.2.8 on 2020-01-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0006_auto_20200127_1027'),
        ('participation', '0006_auto_20200128_1242'),
    ]

    operations = [
    ]
