# Generated by Django 2.2.9 on 2020-02-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0009_team_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tournament',
        ),
    ]
