# Generated by Django 2.2.9 on 2020-02-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0011_team_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='challenge',
        ),
    ]
