# Generated by Django 2.2.9 on 2020-02-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0016_auto_20200210_1801'),
        ('participation', '0012_remove_team_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='challenge',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams', to='challenge.Challenge'),
            preserve_default=False,
        ),
    ]
