# Generated by Django 2.2.9 on 2020-02-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0013_team_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='allow_multi_friendly',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
