# Generated by Django 2.2.9 on 2020-03-09 18:11

import apps.participation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0014_team_allow_multi_friendly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.participation.models.Team.get_team_image_directory),
        ),
    ]
