# Generated by Django 2.2.8 on 2019-12-23 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname_fa', models.TextField(max_length=30)),
                ('firstname_en', models.TextField(max_length=30)),
                ('lastname_fa', models.TextField(max_length=30)),
                ('lastname_en', models.TextField(max_length=30)),
                ('birth_date', models.DateField()),
                ('university', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
