# Generated by Django 2.2.8 on 2019-12-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
    ]
