# Generated by Django 2.2.8 on 2019-12-15 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=50)),
                ('title_fa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('telegram', models.CharField(max_length=200)),
                ('whastsApp', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(choices=[('First', 'first_prize'), ('Second', 'second_prize'), ('Third', 'third_prize')], max_length=100)),
                ('text_fa', models.CharField(choices=[('اول', 'first_prize'), ('دوم', 'second_prize'), ('سوم', 'third_prize')], max_length=100)),
                ('prize_value', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='homepage.Link')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='homepage.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='TimeLineEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(max_length=100)),
                ('text_fa', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Homepage')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Screen'),
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('sponsor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.Sponsor')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Homepage')),
            ],
            bases=('homepage.sponsor',),
        ),
    ]
