# Generated by Django 2.2.8 on 2019-12-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_en', models.CharField(max_length=100)),
                ('header_fa', models.CharField(max_length=100)),
                ('text_en', models.TextField()),
                ('text_fa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_fa', models.CharField(max_length=100)),
                ('prize_en', models.CharField(max_length=100)),
                ('prize_fa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_fa', models.CharField(max_length=100)),
                ('stat_en', models.CharField(max_length=100)),
                ('stat_fa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title_en', models.CharField(max_length=100)),
                ('title_fa', models.CharField(max_length=100)),
                ('text_en', models.TextField()),
                ('text_fa', models.TextField()),
            ],
        ),
    ]
