# Generated by Django 2.2.8 on 2019-12-17 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translation', '0002_documenttest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_timelineevent_text', to='translation.TranslatedText')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_timelineevent_title', to='translation.TranslatedText')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_stat_stat', to='translation.TranslatedText')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_stat_title', to='translation.TranslatedText')),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_prize_prize', to='translation.TranslatedText')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_prize_title', to='translation.TranslatedText')),
            ],
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_intro_header', to='translation.TranslatedText')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_intro_text', to='translation.TranslatedText')),
            ],
        ),
    ]
