# Generated by Django 2.2.8 on 2019-12-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='intro',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prize',
            name='prize',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='prize',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stat',
            name='stat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stat',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
