# Generated by Django 2.2.8 on 2019-12-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_timelineevent_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
        ),
    ]
