# Generated by Django 2.2.8 on 2019-12-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20191226_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
