# Generated by Django 2.2.8 on 2020-02-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_intro_term_of_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_fa', models.CharField(max_length=200)),
                ('comment_en', models.TextField()),
                ('comment_fa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name_en', models.CharField(max_length=200)),
                ('name_fa', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('grade', models.CharField(choices=[('first', 'First Grade'), ('second', 'Second Grade'), ('third', 'Third Grade')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WhyThisEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=300)),
                ('body', models.TextField()),
            ],
        ),
    ]
