# Generated by Django 2.2.8 on 2019-12-16 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translation', '0002_documenttest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_description', to='translation.TranslatedText')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_title', to='translation.TranslatedText')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown', models.TextField(blank=True)),
                ('uuid', models.CharField(blank=True, max_length=20, unique=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resources.Document')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_title', to='translation.TranslatedText')),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='resources.Section')),
                ('subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsection_subtitle', to='translation.TranslatedText')),
            ],
        ),
    ]
