# Generated by Django 2.2.7 on 2019-12-05 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100, unique=True)),
                ('title_fa', models.CharField(blank=True, max_length=100, unique=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_fa', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_fa', models.CharField(blank=True, max_length=100)),
                ('markdown', models.TextField(blank=True)),
                ('uuid', models.CharField(blank=True, max_length=20, unique=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resources.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle_en', models.CharField(max_length=50)),
                ('subtitle_fa', models.CharField(blank=True, max_length=50)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='resources.Section')),
            ],
        ),
    ]
