# Generated by Django 2.2.8 on 2019-12-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_document_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
