# Generated by Django 2.2.7 on 2019-12-01 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20191201_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='resources.Section'),
        ),
    ]
