# Generated by Django 2.2.8 on 2019-12-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_section_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to='document/files/'),
        ),
    ]
