# Generated by Django 2.2.8 on 2019-12-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_document_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='time_to_read',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
