# Generated by Django 2.2.8 on 2019-12-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_document_time_to_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='link_to_colab',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='document/files/'),
        ),
    ]
