# Generated by Django 2.2.9 on 2020-02-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='destination',
            field=models.CharField(max_length=50),
        ),
    ]
