# Generated by Django 2.2.9 on 2020-02-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0002_auto_20200204_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='destination',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='source',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
