# Generated by Django 2.2.8 on 2020-02-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionWithAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=1024)),
                ('question_fa', models.CharField(max_length=1024)),
                ('answer_en', models.CharField(max_length=1024)),
                ('answer_fa', models.CharField(max_length=1024)),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
