# Generated by Django 2.2.8 on 2019-12-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=52428800, upload_to='admin_file_uploads')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
