# Generated by Django 2.2.8 on 2019-12-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='admin_file_uploads'),
        ),
    ]
