# Generated by Django 2.2.8 on 2019-12-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_documenttest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedtext',
            name='content_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='translatedtext',
            name='content_fa',
            field=models.TextField(blank=True, default=''),
        ),
    ]
