# Generated by Django 2.2.8 on 2019-12-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_auto_20191218_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='TText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.TextField(blank=True, default='')),
                ('fa', models.TextField(blank=True, default='')),
            ],
        ),
    ]
