# Generated by Django 2.2.8 on 2020-01-17 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participation', '0001_initial'),
        ('scoreboard', '0001_initial'),
        ('challenge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgroup',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_group', to='participation.Team'),
        ),
        migrations.AddField(
            model_name='submission',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='participation.Team'),
        ),
        migrations.AddField(
            model_name='stage',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='challenge.Tournament'),
        ),
        migrations.AddField(
            model_name='matchteam',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_teams', to='challenge.Match'),
        ),
        migrations.AddField(
            model_name='matchteam',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_team', to='participation.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='map',
            field=models.ForeignKey(on_delete=None, related_name='matches', to='challenge.Map'),
        ),
        migrations.AddField(
            model_name='group',
            name='scoreboard',
            field=models.OneToOneField(on_delete=None, related_name='group', to='scoreboard.Score'),
        ),
        migrations.AddField(
            model_name='gameteam',
            name='game_side',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_teams', to='challenge.GameSide'),
        ),
        migrations.AddField(
            model_name='gameteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_teams', to='participation.Team'),
        ),
        migrations.AddField(
            model_name='gameside',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sides', to='challenge.Game'),
        ),
        migrations.AddField(
            model_name='game',
            name='info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='challenge.Info'),
        ),
        migrations.AddField(
            model_name='game',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='challenge.Match'),
        ),
    ]
