# Generated by Django 2.2.8 on 2020-01-17 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20200117_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='stage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='challenge.Stage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='challenge',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='challenge.Challenge'),
            preserve_default=False,
        ),
    ]
