# Generated by Django 2.2.8 on 2020-01-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20200117_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='challenge.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_team', to='participation.Team'),
        ),
        migrations.AlterField(
            model_name='teamgroup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_group', to='participation.Team'),
        ),
    ]
