# Generated by Django 2.2.8 on 2020-01-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20200118_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='scoreboard',
            field=models.OneToOneField(on_delete=None, related_name='group', to='scoreboard.ScoreBoard'),
        ),
    ]
