# Generated by Django 2.2.8 on 2020-01-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_auto_20200126_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='participant',
            new_name='user',
        ),
    ]
