# Generated by Django 2.2.8 on 2020-01-27 11:57

import apps.challenge.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_auto_20200127_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='file',
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name=apps.challenge.models.get_submission_file_directory)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='challenge.Submission')),
            ],
        ),
    ]
