# Generated by Django 2.2.8 on 2020-01-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_auto_20200127_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfile',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='challenge.Submission'),
        ),
    ]
