# Generated by Django 2.2.8 on 2020-01-27 12:45

import apps.challenge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_auto_20200127_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(default=None, upload_to=apps.challenge.models.get_submission_file_directory),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubmissionFile',
        ),
    ]
