# Generated by Django 2.2.8 on 2020-02-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0012_remove_group_scoreboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='type',
            field=models.CharField(choices=[('similar', 'Two Participants'), ('different', 'Four Participants')], max_length=64),
        ),
    ]
