# Generated by Django 2.2.8 on 2020-02-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0013_auto_20200202_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='run_time',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
