# Generated by Django 2.2.8 on 2020-02-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0014_auto_20200202_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='type',
            field=models.CharField(choices=[('similar', 'Similar Teams'), ('different', 'Different Teams')], max_length=64),
        ),
    ]
