# Generated by Django 2.2.9 on 2020-02-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0016_auto_20200210_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
