# Generated by Django 2.2.9 on 2020-02-14 10:32

import apps.challenge.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0013_team_challenge'),
        ('challenge', '0017_auto_20200213_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamGroup',
            new_name='GroupTeam',
        ),
        migrations.AddField(
            model_name='map',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.challenge.models.Map.map_directory_path),
        ),
        migrations.AddField(
            model_name='map',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='verified',
            field=models.NullBooleanField(),
        ),
    ]
