# Generated by Django 2.2.9 on 2020-02-14 10:52

import apps.challenge.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0018_auto_20200214_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='info',
        ),
        migrations.AddField(
            model_name='game',
            name='infra_game_message',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='infra_token',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='log',
            field=models.FileField(blank=True, null=True, upload_to=apps.challenge.models.Game.get_log_file_directory),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('failed', 'Failed'), ('done', 'Done'), ('waiting', 'Waiting'), ('waiting_accept', 'Waiting to accept'), ('rejected', 'Rejected')], default='waiting', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gameteam',
            name='log',
            field=models.FileField(blank=True, null=True, upload_to=apps.challenge.models.GameTeam.team_single_game_log),
        ),
        migrations.AddField(
            model_name='gameteam',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
