# Generated by Django 2.2.9 on 2020-02-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0019_auto_20200214_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='run_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='submit_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
