# Generated by Django 2.2.9 on 2020-02-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0022_tournament_tournament_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='finished',
            new_name='queued',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
