# Generated by Django 2.2.9 on 2020-02-25 09:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0013_team_challenge'),
        ('challenge', '0024_auto_20200214_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='run_time',
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='challenge.Match'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('multi_play', models.BooleanField(default=False)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobbies', to='challenge.Game')),
                ('teams1', models.ManyToManyField(blank=True, null=True, related_name='lobbies1', to='participation.Team')),
                ('teams2', models.ManyToManyField(blank=True, null=True, related_name='lobbies2', to='participation.Team')),
            ],
        ),
    ]
