# Generated by Django 2.2.9 on 2020-02-25 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0014_team_allow_multi_friendly'),
        ('challenge', '0024_auto_20200214_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='run_time',
        ),
        migrations.AddField(
            model_name='challenge',
            name='code_submit_delay',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='challenge',
            name='friendly_game_delay',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='challenge.Match'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
