# Generated by Django 2.2.9 on 2020-02-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0025_auto_20200225_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='with_friend',
            field=models.BooleanField(default=True),
        ),
    ]
