# Generated by Django 2.2.9 on 2020-02-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0026_auto_20200225_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='multi_play',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lobby',
            name='with_friend',
            field=models.BooleanField(default=True),
        ),
    ]
