# Generated by Django 2.2.9 on 2020-02-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0027_auto_20200225_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='teams',
        ),
    ]
