# Generated by Django 2.2.9 on 2020-02-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0014_team_allow_multi_friendly'),
        ('challenge', '0028_remove_lobby_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='teams1',
            field=models.ManyToManyField(blank=True, null=True, related_name='lobbies1', to='participation.Team'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='teams2',
            field=models.ManyToManyField(blank=True, null=True, related_name='lobbies2', to='participation.Team'),
        ),
    ]
