# Generated by Django 2.2.9 on 2020-02-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0029_auto_20200225_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='challenge.Match'),
        ),
    ]
