# Generated by Django 2.2.9 on 2020-03-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0030_auto_20200225_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchteam',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
