# Generated by Django 2.2.9 on 2020-03-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0033_match_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
    ]
