# Generated by Django 2.2.9 on 2020-03-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0034_tournament_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='match_bet_percentage',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
