# Generated by Django 2.2.9 on 2020-03-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0035_tournament_match_bet_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameteam',
            name='scoreboard_score',
            field=models.FloatField(default=0.0),
        ),
    ]
