# Generated by Django 2.2.9 on 2020-03-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0036_gameteam_scoreboard_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='can_submit',
            field=models.BooleanField(default=True),
        ),
    ]
