# Generated by Django 2.2.9 on 2020-03-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0038_challenge_can_change_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchteam',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
