# Generated by Django 2.2.9 on 2020-03-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0039_auto_20200305_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
