# Generated by Django 2.2.9 on 2020-03-06 08:02

import apps.challenge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0040_auto_20200305_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.challenge.models.get_submission_file_directory),
        ),
    ]
