# Generated by Django 2.2.9 on 2020-03-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0041_auto_20200306_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='download_link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
