# Generated by Django 2.2.9 on 2020-03-06 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0042_submission_download_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunTournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='runs', to='challenge.Tournament')),
            ],
        ),
    ]
