# Generated by Django 2.2.9 on 2020-03-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0043_runtournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtournament',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
