# Generated by Django 2.2.9 on 2020-03-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0044_runtournament_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_map',
        ),
    ]
