# Generated by Django 2.2.9 on 2020-03-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0045_remove_tournament_tournament_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_maps',
            field=models.ManyToManyField(related_name='tournaments', to='challenge.Map'),
        ),
    ]
