# Generated by Django 2.2.9 on 2020-03-07 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0046_tournament_tournament_maps'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='runs', to='challenge.Group')),
            ],
        ),
    ]
