# Generated by Django 2.2.9 on 2020-03-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0047_rungroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
