# Generated by Django 2.2.9 on 2020-03-09 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0049_auto_20200308_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendly_matches', to='challenge.Game'),
        ),
    ]
