# Generated by Django 2.2.9 on 2020-03-09 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0050_auto_20200309_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobbies', to='challenge.Challenge'),
        ),
    ]
