# Generated by Django 2.2.9 on 2020-03-12 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0015_auto_20200309_1811'),
        ('challenge', '0052_auto_20200311_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='can_friendly_game',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RunFinalMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_matches1', to='participation.Team')),
                ('maps', models.ManyToManyField(related_name='run_matches', to='challenge.Map')),
                ('second_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_matches2', to='participation.Team')),
            ],
        ),
    ]
