# Generated by Django 2.2.9 on 2020-03-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0053_auto_20200312_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='runfinalmatch',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, related_name='run_matches', to='challenge.Game'),
        ),
    ]
