# Generated by Django 2.2.9 on 2020-03-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0054_runfinalmatch_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runfinalmatch',
            name='games',
        ),
        migrations.AddField(
            model_name='runfinalmatch',
            name='games',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
