# Generated by Django 2.2.9 on 2020-03-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0055_auto_20200312_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runfinalmatch',
            name='maps',
        ),
    ]
