# Generated by Django 2.2.9 on 2020-03-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0056_remove_runfinalmatch_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='runfinalmatch',
            name='maps',
            field=models.CharField(default='12 13 14', max_length=100),
        ),
    ]
