# Generated by Django 2.2.9 on 2020-03-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0057_runfinalmatch_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
