# Generated by Django 2.2.8 on 2020-01-24 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_auto_20200124_0930'),
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='participation.Team'),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
