# Generated by Django 2.2.8 on 2020-01-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
