# Generated by Django 2.2.8 on 2020-02-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0012_remove_group_scoreboard'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('scoreboard', '0003_row_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoreboard',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='scoreboard',
            name='tournament',
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='freeze',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoreboard',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_scoreboard.scoreboard_set+', to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='GroupScoreBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoreboard', to='challenge.Group')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeScoreBoard',
            fields=[
                ('scoreboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scoreboard.ScoreBoard')),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoreboard', to='challenge.Challenge')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('scoreboard.scoreboard',),
        ),
    ]
