# Generated by Django 2.2.8 on 2020-02-02 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_auto_20200202_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupscoreboard',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='groupscoreboard',
            name='id',
        ),
        migrations.AddField(
            model_name='groupscoreboard',
            name='scoreboard_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scoreboard.ScoreBoard'),
            preserve_default=False,
        ),
    ]
