# Generated by Django 2.2.9 on 2020-02-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0005_auto_20200202_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='row',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='row',
            name='score',
            field=models.IntegerField(default=1000),
        ),
    ]
