# Generated by Django 2.2.9 on 2020-02-14 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0006_auto_20200214_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='participation.Team'),
        ),
    ]
