# Generated by Django 2.2.9 on 2020-02-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0007_auto_20200214_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
