# Generated by Django 2.2.9 on 2020-03-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0008_row_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupscoreboard',
            name='calculated',
            field=models.BooleanField(default=False),
        ),
    ]
