# Generated by Django 2.2.9 on 2020-03-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0009_groupscoreboard_calculated'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='draws',
            field=models.IntegerField(default=0),
        ),
    ]
