# Generated by Django 2.2.9 on 2020-03-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0010_row_draws'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='score',
        ),
    ]
