# Generated by Django 2.2.9 on 2020-03-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0011_remove_row_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='score',
            field=models.FloatField(default=1000.0),
        ),
    ]
