# Generated by Django 2.2.9 on 2020-03-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0012_row_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='type',
            field=models.CharField(default='challenge', max_length=20),
        ),
    ]
