# Generated by Django 2.2.9 on 2020-03-03 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0013_scoreboard_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendlyScoreBoard',
            fields=[
                ('scoreboard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scoreboard.ScoreBoard')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('scoreboard.scoreboard',),
        ),
    ]
