# Generated by Django 2.2.9 on 2020-03-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0013_auto_20200303_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='score',
            field=models.FloatField(db_index=True, default=2000.0),
        ),
    ]
