# Generated by Django 2.2.9 on 2020-03-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0013_friendlyscoreboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='type',
            field=models.CharField(default='challenge', max_length=20),
        ),
    ]
