# Generated by Django 2.2.9 on 2020-03-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0014_auto_20200303_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='type',
            field=models.CharField(default='challenge', max_length=20),
        ),
    ]
